// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWTcZUBWeTpLQwu46wEAaejghLPXTivQ0',
    appId: '1:624765507094:web:d0f3ca4b6d0ad44b750737',
    messagingSenderId: '624765507094',
    projectId: 'vetconnect-d2717',
    authDomain: 'vetconnect-d2717.firebaseapp.com',
    storageBucket: 'vetconnect-d2717.firebasestorage.app',
    measurementId: 'G-YDLF5DE0NN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAovPFQs8CG8teSB8dwqlKt62PGuLqRDd8',
    appId: '1:624765507094:android:a2c3d0c806bb0190750737',
    messagingSenderId: '624765507094',
    projectId: 'vetconnect-d2717',
    storageBucket: 'vetconnect-d2717.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl33Zt6S2hPKYAtCr-Wz0k_WGuyeFkNY4',
    appId: '1:624765507094:ios:eecc51d4cf01f6b7750737',
    messagingSenderId: '624765507094',
    projectId: 'vetconnect-d2717',
    storageBucket: 'vetconnect-d2717.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl33Zt6S2hPKYAtCr-Wz0k_WGuyeFkNY4',
    appId: '1:624765507094:ios:eecc51d4cf01f6b7750737',
    messagingSenderId: '624765507094',
    projectId: 'vetconnect-d2717',
    storageBucket: 'vetconnect-d2717.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWTcZUBWeTpLQwu46wEAaejghLPXTivQ0',
    appId: '1:624765507094:web:c7a82c409012a78f750737',
    messagingSenderId: '624765507094',
    projectId: 'vetconnect-d2717',
    authDomain: 'vetconnect-d2717.firebaseapp.com',
    storageBucket: 'vetconnect-d2717.firebasestorage.app',
    measurementId: 'G-8B29GNS0NB',
  );
}
